(in-package "ACL2")

(include-book "std/util/defrule" :dir :system)
(include-book "centaur/fty/top" :dir :system)
(include-book "std/util/bstar" :dir :system)
(include-book "std/typed-lists/top" :dir :system)
(include-book "std/lists/top" :dir :system)
(include-book "std/basic/inductions" :dir :system)

(defun boolean-variable-values(variable-count variable-values)
    (if
        (or
            (not
                (integerp
                    variable-count
                )
            )
            (not
                (true-listp
                    variable-values
                )
            )
        )
        nil
        (if
            (>=
                0
                variable-count
            )
            nil
            (if
                (>=
                    1
                    variable-count
                )
                (list
                    (cons
                         t
                         variable-values
                    )
                    (cons
                         nil
                         variable-values
                    )
                )
                (append
                    (boolean-variable-values
                        (-
                            variable-count
                            1
                        )
                        (cons
                            t
                            variable-values
                        )
                    )
                    (boolean-variable-values
                        (-
                            variable-count
                            1
                        )
                        (cons
                            nil
                            variable-values
                        )
                    )
                )
            )
        )
    )
)

(defrule boolean-variable-values-type
    (true-listp
         (boolean-variable-values
             variable-count
             nil
         )
    )
    :rule-classes :type-prescription
)

(defun boolean-variable-values-boolean-listp(l)
    (if
        (not
            (true-listp
                l
            )
        )
        nil
        (if
            (endp
                l
            )
            t
            (and
                (boolean-listp
                    (car
                        l
                    )
                )
                (boolean-variable-values-boolean-listp
                    (cdr
                        l
                    )
                )
            )
        )
    )
)

(defrule boolean-variable-values-element-type-general
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
            (boolean-listp
                l
            )
        )
        (boolean-variable-values-boolean-listp
            (boolean-variable-values
                variable-count
                l
            )
        )
    )
    :rule-classes :type-prescription
    :induct
            (boolean-variable-values
                variable-count
                l
            )
    :hints
    (
        ("Subgoal *1/2"
            :expand
            (boolean-variable-values
                variable-count
                l
            )
        )
    )
)

(defrule boolean-variable-values-element-type
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
        )
        (boolean-variable-values-boolean-listp
            (boolean-variable-values
                variable-count
                nil
            )
        )
    )
    :rule-classes :type-prescription
    :use
    (
        (:instance
            boolean-variable-values-element-type-general
            (
               l
               nil
            )
        )
    )
)

(defrule boolean-variable-values-cdr
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
            (boolean-variable-values-boolean-listp
                variable-values
            )
        )
        (boolean-variable-values-boolean-listp
            (cdr
                variable-values
            )
        )
    )
    :rule-classes :type-prescription
)

(defrule boolean-variable-values-cdr-type
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
        )
        (boolean-variable-values-boolean-listp
            (cdr
                (boolean-variable-values
                    variable-count
                    nil
                )
            )
        )
    )
    :rule-classes :type-prescription
)

(defrule boolean-variable-values-car
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
            (not
                (endp
                    variable-values
                )
            )
            (boolean-variable-values-boolean-listp
                variable-values
            )
        )
        (boolean-listp
            (car
                variable-values
            )
        )
    )
    :rule-classes :type-prescription
)

(defrule boolean-variable-values-car-type
    (implies
        (and
            (integerp
                variable-count
            )
            (>
                variable-count
                0
            )
            (not
                (endp
                    (boolean-variable-values
                        variable-count
                        nil
                    )
                )
            )
        )
        (boolean-listp
            (car
                (boolean-variable-values
                    variable-count
                    nil
                )
            )
        )
    )
    :rule-classes :type-prescription
)

(defun formula-sat-column(implication-graph-transitive-closure-column-index implication-graph-transitive-closure-row-index variable-values variable-count implication-graph-transitive-closure)
    (declare
        (xargs
            :measure
            (nfix
                (+
                    implication-graph-transitive-closure-column-index
                    1
                )
            )
        )
    )
    (if
        (or
            (not
                (integerp
                    variable-count
                )
            )
            (not
                (>
                    variable-count
                    0
                )
            )
            (not
                (integerp
                    implication-graph-transitive-closure-column-index
                )
            )
            (not
                (<
                    implication-graph-transitive-closure-column-index
                    variable-count
                )
            )
            (not
                (boolean-listp
                    variable-values
                )
            )
            (not
                (integer-listp
                    implication-graph-transitive-closure
                )
            )
            (not
                (=
                    (len
                        implication-graph-transitive-closure
                    )
                    (*
                        4
                        (*
                            variable-count
                            variable-count
                        )
                    )
                )
            )
            (not
                (integerp
                    implication-graph-transitive-closure-row-index
                )
            )
            (not
                (<=
                    0
                    implication-graph-transitive-closure-row-index
                )
            )
            (not
                (<
                    implication-graph-transitive-closure-row-index
                    variable-count
                )
            )
        )
        nil
        (if
            (<
                implication-graph-transitive-closure-column-index
                0
            )
            t
            (and
                (if
                    (=
                        (nth
                            (+
                                (*
                                    implication-graph-transitive-closure-row-index
                                    (*
                                        variable-count
                                        2
                                    )
                                )
                                implication-graph-transitive-closure-column-index
                            )
                            implication-graph-transitive-closure
                        )
                        1
                    )
                    (implies
                        (nth
                            implication-graph-transitive-closure-row-index
                            variable-values
                        )
                        (nth
                            implication-graph-transitive-closure-column-index
                            variable-values
                        )
                    )
                    t
                )
                (if
                    (=
                        (nth
                            (+
                                (*
                                    (+
                                        implication-graph-transitive-closure-row-index
                                        variable-count
                                    )
                                    (*
                                        variable-count
                                        2
                                    )
                                )
                                implication-graph-transitive-closure-column-index
                            )
                            implication-graph-transitive-closure
                        )
                        1
                    )
                    (implies
                        (not
                            (nth
                                implication-graph-transitive-closure-row-index
                                variable-values
                            )
                        )
                        (nth
                            implication-graph-transitive-closure-column-index
                            variable-values
                        )
                    )
                    t
                )
                (if
                    (=
                        (nth
                            (+
                                (*
                                    implication-graph-transitive-closure-row-index
                                    (*
                                        variable-count
                                        2
                                    )
                                )
                                (+
                                    implication-graph-transitive-closure-column-index
                                    variable-count
                                )
                            )
                            implication-graph-transitive-closure
                        )
                        1
                    )
                    (implies
                        (nth
                            implication-graph-transitive-closure-row-index
                            variable-values
                        )
                        (not
                            (nth
                                implication-graph-transitive-closure-column-index
                                variable-values
                            )
                        )
                    )
                    t
                )
                (if
                    (=
                        (nth
                            (+
                                (*
                                    (+
                                        implication-graph-transitive-closure-row-index
                                        variable-count
                                    )
                                    (*
                                        variable-count
                                        2
                                    )
                                )
                                (+
                                    implication-graph-transitive-closure-column-index
                                    variable-count
                                )
                            )
                            implication-graph-transitive-closure
                        )
                        1
                    )
                    (implies
                        (not
                            (nth
                                implication-graph-transitive-closure-row-index
                                variable-values
                            )
                        )
                        (not
                            (nth
                                implication-graph-transitive-closure-column-index
                                variable-values
                            )
                        )
                    )
                    t
                )
                (formula-sat-column
                    (-
                        implication-graph-transitive-closure-column-index
                        1
                    )
                    implication-graph-transitive-closure-row-index
                    variable-values
                    variable-count
                    implication-graph-transitive-closure
                )
            )
        )
    )
)

(defun formula-sat(implication-graph-transitive-closure-row-index variable-values variable-count implication-graph-transitive-closure)
    (declare
        (xargs
            :measure
            (nfix
                (+
                    implication-graph-transitive-closure-row-index
                    1
                )
            )
        )
    )
    (if
        (or
            (not
                (integerp
                    variable-count
                )
            )
            (not
                (>
                    variable-count
                    0
                )
            )
            (not
                (boolean-listp
                    variable-values
                )
            )
            (not
                (integer-listp
                    implication-graph-transitive-closure
                )
            )
            (not
                (=
                    (len
                        implication-graph-transitive-closure
                    )
                    (*
                        4
                        (*
                            variable-count
                            variable-count
                        )
                    )
                )
            )
            (not
                (integerp
                    implication-graph-transitive-closure-row-index
                )
            )
            (not
                (<
                    implication-graph-transitive-closure-row-index
                    variable-count
                )
            )
        )
        nil
        (if
            (<
                implication-graph-transitive-closure-row-index
                0
            )
            t
            (and
                (formula-sat-column
                    (-
                        variable-count
                        1
                    )
                    implication-graph-transitive-closure-row-index
                    variable-values
                    variable-count
                    implication-graph-transitive-closure
                )
                (formula-sat
                    (-
                        implication-graph-transitive-closure-row-index
                        1
                    )
                    variable-values
                    variable-count
                    implication-graph-transitive-closure
                )
            )
        )
    )
)

(defun twosat-solver(variable-values variable-count implication-graph-transitive-closure)
    (if
        (or
            (not
                (integerp
                    variable-count
                )
            )
            (not
                (>
                    variable-count
                    0
                )
            )
            (not
                (integer-listp
                    implication-graph-transitive-closure
                )
            )
            (not
                (boolean-variable-values-boolean-listp
                    variable-values
                )
            )
            (not
                (=
                    (len
                        implication-graph-transitive-closure
                    )
                    (*
                        4
                        (*
                            variable-count
                            variable-count
                        )
                    )
                )
            )
        )
        nil
        (if
            (endp
                variable-values
            )
            nil
            (or
                (formula-sat
                    (-
                        variable-count
                        1
                    )
                    (car
                        variable-values
                    )
                    variable-count
                    implication-graph-transitive-closure
                )
                (twosat-solver
                    (cdr
                        variable-values
                    )
                    variable-count
                    implication-graph-transitive-closure
                )
            )
        )
    )
)

(defrule formula-unsat-column
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat-column
                variable-index
                variable-index
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :do-not-induct t
    :expand
    (formula-sat-column
        variable-index
        variable-index
        variable-values
        variable-count
        implication-graph-transitive-closure
    )
)

(defrule formula-unsat-column-general
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<=
                variable-index
                j
            )
            (integerp
                j
            )
            (<
                j
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat-column
                j
                variable-index
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :induct (dec-induct j)
)

(defrule formula-unsat-column-check
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat-column
                (-
                    variable-count
                    1
                )
                variable-index
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :use
    (
        (:instance
            formula-unsat-column-general
            (
                j
                (-
                    variable-count
                    1
                )
            )
        )
    )
)

(defrule formula-unsat-row
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat
                variable-index
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :do-not-induct t
    :expand
    (formula-sat
        variable-index
        variable-values
        variable-count
        implication-graph-transitive-closure
    )
)

(defrule formula-unsat-row-general
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<=
                variable-index
                j
            )
            (integerp
                j
            )
            (<
                j
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat
                j
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :induct (dec-induct j)
)

(defrule formula-unsat-row-check
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (boolean-listp
                variable-values
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (formula-sat
                (-
                    variable-count
                    1
                )
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
    :use
    (
        (:instance
            formula-unsat-row-general
            (
                j
                (-
                    variable-count
                    1
                )
            )
        )
    )
)

(defrule twosat-unsat-general
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
            (boolean-variable-values-boolean-listp
                variable-values
            )
        )
        (not
            (twosat-solver
                variable-values
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
)

(defrule twosat-unsat
    (implies
        (and
            (integerp
                variable-index
            )
            (<=
                0
                variable-index
            )
            (<
                variable-index
                variable-count
            )
            (=
                (nth
                    (+
                        (*
                            variable-index
                            (*
                                variable-count
                                2
                            )
                        )
                        (+
                            variable-index
                            variable-count
                        )
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (=
                (nth
                    (+
                        (*
                            (+
                                variable-index
                                variable-count
                            )
                            (*
                                variable-count
                                2
                            )
                        )
                        variable-index
                    )
                    implication-graph-transitive-closure
                )
                1
            )
            (integerp
                variable-count
            )
            (<
                0
                variable-count
            )
            (integer-listp
                implication-graph-transitive-closure
            )
            (=
                (len
                    implication-graph-transitive-closure
                )
                (*
                    4
                    (*
                        variable-count
                        variable-count
                    )
                )
            )
        )
        (not
            (twosat-solver
                (boolean-variable-values
                    variable-count
                    nil
                )
                variable-count
                implication-graph-transitive-closure
            )
        )
    )
    :rule-classes :rewrite
)